#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;
use Illuminate\Foundation\Configuration\ApplicationBuilder;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;

define('LARAVEL_START', microtime(true));

require_once __DIR__.'/vendor/autoload.php';

/** @var ApplicationBuilder $app */
$app = require_once __DIR__.'/bootstrap/app.php';

$input = new ArgvInput($argv);
$output = new ConsoleOutput();

$status = $app->handleCommand($input, $output);

exit($status);
